module.exports={
    containerFull: {
        width: "100%",
        height: "100%",
        backgroundColor: "rgba(0,0,0,.9)",
        alignItems: "center",
        justifyContent: "center",
      },
      goback: {
        flexDirection: "row",
        position: "absolute",
        top: 50,
        left: 20,
        alignItems: "center",
      },
      formHead2: {
        fontSize: 20,
        color: "white",
        opacity:.6,
        textAlign: "center",
      },
      formInput: {
        backgroundColor: "rgba(255,255,255,1)",
        width: "80%",
        padding: 15,
        fontSize: 20,
        borderRadius: 20,
      },
      formbtn: {
        backgroundColor: "black",
        borderColor: "white",
        paddingVertical: 10,
        borderRadius: 15,
        borderWidth: 1.5,
        borderColor: "white",
        width: "80%",
        alignItems: "center",
        marginTop:20,
      },
}